### ISSUE TITLE
Mob Spawning

### ISSUE THREAD

**Issue by augesrob** [Nukkit-coders/mob-plugin#3]
### Issue Description

Mobs are spawning where they would not normally spawn
On the water, in dirt blocks, and other areas.

### Steps to Reproduce the Issue

1. Any Gamemode
2. Walking around until you see them spawn

### OS and Versions

* Nukkit Version: 1.2.5
* Client: Windows10

#### Config.yml
```
entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: 

max-spawns:
  bat: 10
  blaze: 5
  cave-spider: 5
  chicken: 15
  cow: 10
  creeper: 5
  donkey: 6
  enderman: 3
  ghast: 4
  horse: 8
  iron-golem: 3
  mooshroom: 5
  mule: 6
  ocelot: 15
  pig: 7
  pig-zombie: 3
  rabbit: 10
  silverfish: 6
  sheep: 10
  skeleton: 2
  skeleton-horse: 2
  snow-golem: 3
  spider: 4
  squid: 3
  wolf: 6
  witch: 0
  zombie: 5
  zombie-horse: 5
  zombie-villager: 5

```
