### ISSUE TITLE
It seems that wolfs won't attack me properly when I hit them

### ISSUE THREAD

**Issue by twostay** [Nukkit-coders/mob-plugin#53]
### Issue Description

So when I punch a wolf, it'll run to me and tries to attack me, however it will only do the act of attacking me but causing no damage, and if I check the consloe, error messages appear(lots of repeating ones)

### Steps to Reproduce the Issue
Put a wolf down punch them

### Nukkit Version and Client Version

* Nukkit Version: 1.2.10#95
* Client: Ios

#### Config.yml
```
entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: "exampleworld"

max-spawns:
  bat: 2
  blaze: 0
  chicken: 6
  cow: 5
  creeper: 3
  enderman: 1
  ghast: 0
  husk: 3
  horse: 1
  mooshroom: 0
  ocelot: 2
  pig: 5
  polarbear: 2
  rabbit: 4
  stray: 3 
  sheep: 6
  skeleton: 3
  spider: 4
  wolf: 2
  zombie: 4


```
### Crashdump, Backtrace or Other Files

```
![bug1](https://user-images.githubusercontent.com/36668182/36429403-932e0b0a-168d-11e8-89b7-8832175f12c6.JPG)

<!--- Copy and paste your backtrace here... -->
```It's in the image
